Bank_Account_Ver1
victoriamedv/JavaScriptNew pull request #4
Opened 2024-03-07 21:13 UTC by victoriamedv

2024-03-08 22:11 UTC, burtovoy requested changes

2024-03-08 22:11 UTC, burtovoy commented on bank_account/bank-account.js
> +      this.isOpen = true;
Много странных пробелов в файле. Линтер пропускает такое?

2024-03-12 19:57 UTC, victoriamedv commented on bank_account/bank-account.js
> +      this.isOpen = true;
У меня возникла проблема из-за отсутсвия линта в старых ветках, поэтому коммитами я пыталась сдвинуть дальний пуш.

2024-03-13 21:30 UTC, burtovoy commented
конфликты

2024-03-13 21:30 UTC, burtovoy requested changes
конфликты

2024-03-13 22:45 UTC, victoriamedv commented
исправила

2024-03-15 16:16 UTC, merged